# I really dislike to install software on my host machine
# when it is not a native package of my OS.
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  misenplace:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer
    # folder. Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: misenplace
    restart: unless-stopped
    network_mode: "host"

    volumes:
      - ../config:/config:z
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/workspace:Z
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /run/podman/podman.sock:/var/run/podman/podman.sock:Z

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
